### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by mathematicalmichael** [mathematicalmichael/slumlords#1]
- [ ] Create github milestones for initial release

- [ ] link namecheap domain to github, set up website (make live). 

- [x] strip site/theme of extraneous references, demo content, images, etc

  - [ ] replace images

  - [x] get some "pages" up to replace demo ones.

- [ ] Denver Slumlords branding throughout site

- [ ] Decide on font choice

- [ ] Set up Disqus 

  - [x] account creation (DenverSlumlords)

  - [ ] code into the website

- [ ] bing verification (?)

- [ ] Google verification in `config.toml` and Analytics.

- [x] Set up email (denverslumlords@gmail.com)

- [ ] Set up instagram

- [ ] Create plan for announcement

  - [ ] reddit? hackernews? journalists on twitter, etc

  - [ ] timeline

- [ ] formspring or something similar for submission email
  
  - [ ] if user refreshes, does content get purged?

- [ ] set up contribution pipeline (maybe push a development version of the website somewhere using Travis?) new posts as issues for editing (that way we can edit/format contributing posts through github interface, do so on-the-go). maybe PRs?

- [x] social sharing icons (decide on subset chosen in `config.toml`

- [ ] fix WARNings in `hugo==0.55` ... seems easy to do based on the messages printed out. All deprecation warnings. 

  - [ ] do we ...
    - [ ] just edit theme directly (as I've done to suppress copyright), or 
     - [ ] place edited copies of files in directories that are prioritized?

- [ ] author names? (anonymous? first?) 

- [ ] FIGURE OUT COPYRIGHT. This is confusing... the theme has references to `copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." ` in the`config.toml` file, but the repo itself is under MIT. This makes me think that the statement is simply a default copyright notice included in the example website. AKA we should replace this line with our own. 

- [ ] what is gittalk? (see very bottom of `config.toml`

- [ ] look over/verify current `sitemap` and `blackfriday` settings in `config.toml` .. and `paginate.`

**Comment by mathematicalmichael** [comment]
- [x] change authorship formatting 

- [x] post metadata (get rid of reading time, re-format date)

- [x] format of categories list pages (`partials/list.html`)

- [x] test some tags and categories
